// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "signin": "Sign In",
    "signin_description": "Use your email and password to sign in",
    "email": "Email Address",
    "password": "Password",
    "dont_have_account": "Don't have an account?",
    "signup": "Sign Up",
    "free": "for free",
    "sidebar_title": "Prompt Pilot",
    "sidebar_description": "Your conversations will appear here once you start chatting!",
    "greeting_hearder": "Hello there!",
    "greeting_description": "How can I help you today?"
};
export default messages;